name: main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print python version
        run: python -VV
      - name: Install dependencies
        run: pip install -e .[test]
      - name: Test with pytest
        run: pytest --cov --cov-report=html
      - name: Generate coverage badge
        run: coverage-badge -o htmlcov/badge.svg
      - name: Upload htmlcov
        if: ${{ matrix.python-version == '3.10' }}
        uses: actions/upload-artifact@v3
        with:
          name: htmlcov
          path: htmlcov
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: pip install -e .[test,hack]
      - name: Run mypy
        run: mypy
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies for sphinx
        run: pip install -e .[docs]
      - name: Run sphinx
        run: sphinx-build sphinx-source sphinx-output -W --keep-going
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: sphinx-output
